name: DevOps UTS DT206 CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .
          docker images

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: echo "Running Unit Tests..."

      - name: Linting Code
        run: echo "Linting Code... No Issues Found"
